version: "last"
services:
  n8n:
    build:
      ./n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env

volumes:
  n8n_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./n8n_data


